version: "3"
services:
  jupyterlab:
    container_name: cryptocurrency-trading-with-shadow_jupyter
    platform: linux/amd64
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "58888:8888"
    volumes:
      - "./src:/src"
    # command: "jupyter lab --no-browser --ip=0.0.0.0 --allow-root"
    command: "jupyter lab --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token=''"
